sudo: 'required'

services:
  - 'docker'

before_install:
  - './.travis/main.sh'

script:
  - docker build -t innovanon/logo .
  #- make
  #- 'make test'
  #- 'make image'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push -t innovanon/logo ;
    fi
      #make push-image ;

notifications:
  email: true

