version: 2.1
jobs:
  build:
    docker: 
      #- image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      - image: innovanon/poobuntu-ci:latest
    #parallelism: 4
    steps:
      - run:
          command: |
            set -exu
            echo -e "$GPG_KEY" | gpg --import
      - run:
          command: |
            set -exu
            apt-fast install bc imagemagick caca-utils stegosuite zpaq lrzip makeself
            sed -i 's#^\( *<policy domain="resource" name="disk" value="\).*\("/>\)$#\110GiB\1#' /etc/ImageMagick-6/policy.xml
            sed -i 's#^\( *<policy domain="resource" name="memory" value="\).*\("/>\)$#\11GiB\1#' /etc/ImageMagick-6/policy.xml

            git clone --recursive https://github.com/InnovAnon-Inc/${CIRCLE_PROJECT_REPONAME}.git
            cd ${CIRCLE_PROJECT_REPONAME}
            #PACKAGE=${CIRCLE_PROJECT_REPONAME,,}
            #
            #[ ! -z "`git tag`" ] || git tag v1.0
            #git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' || git tag v1.0
            ##revisioncount=$(expr `git log --oneline | wc -l` + 1)
            #revisioncount=`git log --oneline | wc -l`
            #cleanversion="`git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//`"
            #VERSION="$cleanversion.$revisioncount"
            
            rm -v LICENSE README.md .gitignore
            #tar cf archive.tar --exclude archive.tar .
            tar cf -                  \
              --exclude archive.tar   \
              --exclude .circleci     \
              --exclude-vcs           \
              --exclude-vcs-ignores   \
              --absolute-names        \
              --group=nogroup         \
              --mtime=0               \
              --no-acls               \
              --numeric-owner         \
              --owner=nobody          \
              --sort=name             \
              --sparse              . |
            ( mkdir -v /tmp/archive &&
              cd       /tmp/archive &&
              tar xf   - )
            makeself --nocomp /tmp/archive archive.tar quine \
            make -j$(nproc)
            #env RECP=InnovAnon-Inc@protonmail.com make -j$(nproc)

            #RECP=InnovAnon-Inc@protonmail.com make -j$(nproc)
            make -j$(nproc)

            make -j$(nproc) clean
            #rm -v Makefile *.url LICENSE README.md
            rm -v Makefile *.url shiva.jpg kali.jpg stego.mk archive.*
            #rm -rf .git .circleci

            for k in * ; do
              gpg --local-user 53F31F9711F06089\! --sign $k
            done

            PACKAGE=${CIRCLE_PROJECT_REPONAME,,}

            [ ! -z "`git tag`" ] || git tag v1.0
            git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' || git tag v1.0
            #revisioncount=$(expr `git log --oneline | wc -l` + 1)
            revisioncount=`git log --oneline | wc -l`
            cleanversion="`git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//`"
            VERSION="$cleanversion.$revisioncount"

            mkdir -v ../tmp
            mv -v *  ../tmp
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} ../tmp

            #git remote set-url origin https://github.com:${GITHUB_TOKEN}@github.com/InnovAnon-Inc/${CIRCLE_PROJECT_REPONAME}.git
            #git tag v$VERSION
            #git push
            #git push --tags
            #
            #github-release release --security-token $GITHUB_TOKEN --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME \
            #  --tag v$VERSION
            #
            #for k in * ; do
            #github-release upload  --security-token $GITHUB_TOKEN --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME \
            #  --tag v$VERSION --name $k --file $k
            #done
workflows:
  version: 2.1
  commit:
    jobs:
      - build
  #approval:
  #  jobs:
  #    - hold:
  #        type: approval
      #- deploy:
      #    requires:
      #      - hold

