version: 2.1
jobs:
  build:
    docker: 
      - image: innovanon/logo-builder-ci
    steps:
      - run:
          name: Checkout Project
          command: |
            $SHELL -l -c "git clone --recursive https://github.com/InnovAnon-Inc/${CIRCLE_PROJECT_REPONAME}.git"
      - run:
          name: Check Scripts
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}
            shellcheck -ax sign.sh
      - run:
          name: Build Project
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}
            #RECP=InnovAnon-Inc@protonmail.com make -j$(nproc)
            #$SHELL -l -c "make -j1"
            $SHELL -l -c "make -j$(nproc)"
      - run:
          name: Import GPG Key
          command: |
            set -u
            echo -e "$GPG_KEY" | \
            gpg --import
      - run:
          name: Sign Project
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}
           
            mv -v sign.sh /usr/local/bin
            
            mkdir -v    /tmp/logo
            mv -v out/* /tmp/logo/
            cd          /tmp/logo

            sign.sh
      - run:
          name: Release Project
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}

            [ ! -z "`git tag`" ] || \
            git tag v1.0
            git describe --tags --long | \
            grep -o '^v[^.]*\.[^.-]*' || \
            git tag v1.0
            revisioncount="$(git log --oneline | wc -l)"
            cleanversion="$(git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//)"
            VERSION="$cleanversion.$revisioncount"

            #ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} ../tmp
            $SHELL -l -c "ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} /tmp/logo"
            #$SHELL -l -c "env GOPATH=${HOME}/go PATH=${PATH}:${HOME}/go/bin ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} /tmp/logo"
      - run:
          name: Update Home Page
          command: |
            $SHELL -l -c 'git clone --depth=1 --recursive https://github.com/InnovAnon-Inc/InnovAnon-Inc.github.io.git'
            #cp -v ../tmp/logo/favicon.ico             assets/images/favicon.ico
            #cp -v ../tmp/logo/logo-visible.png        assets/images/logo.png
            #cp -v ../tmp/logo/logo-visible.png               images/3600x3600.png

            #        apple-touch-icon-114x114-precomposed.png \
            #        apple-touch-icon-120x120-precomposed.png \
            #        apple-touch-icon-144x144-precomposed.png \
            #        apple-touch-icon-152x152-precomposed.png \
            #        apple-touch-icon-180x180-precomposed.png \
            #        apple-touch-icon-57x57-precomposed.png   \
            #        apple-touch-icon-60x60-precomposed.png   \
            #        apple-touch-icon-72x72-precomposed.png   \
            #        apple-touch-icon-76x76-precomposed.png   \
            #        apple-touch-icon-precomposed.png         \
            #        bio-photo.jpg                            \
            #        apple-touch-icon.png                     \
            DIR="$(readlink -f "$(pwd)")/InnovAnon-Inc.github.io"
            cd /tmp/logo
            mv -v android-chrome-144x144.png               \
                  android-chrome-192x192.png               \
                  android-chrome-256x256.png               \
                  android-chrome-36x36.png                 \
                  android-chrome-384x384.png               \
                  android-chrome-48x48.png                 \
                  android-chrome-72x72.png                 \
                  android-chrome-96x96.png                 \
                  apple-touch-icon-114x114.png             \
                  apple-touch-icon-120x120.png             \
                  apple-touch-icon-144x144.png             \
                  apple-touch-icon-152x152.png             \
                  apple-touch-icon-180x180.png             \
                  apple-touch-icon-57x57.png               \
                  apple-touch-icon-60x60.png               \
                  apple-touch-icon-72x72.png               \
                  apple-touch-icon-76x76.png               \
                  favicon-16x16.png                        \
                  favicon-194x194.png                      \
                  favicon-32x32.png                        \
                  favicon.ico                              \
                  mstile-144x144.png                       \
                  mstile-150x150.png                       \
                  mstile-310x150.png                       \
                  mstile-310x310.png                       \
                  mstile-70x70.png                         \
                  safari-pinned-tab.svg                    \
                  "$DIR/assets/images"
            mv -v logo-small-animated.gif                  \
                  "$DIR/assets/images/logo.gif"
            cd    "$DIR/assets/images"
            # manually managed math on black
            #ln -sv logo-visible.png 3600x3600.png
            ln -sv logo-visible.png logo.png
            cd    "$DIR"

            git config --global user.email "InnovAnon-Inc@protonmail.com"
            git config --global user.name  "Innovations Anonymous"
            git add .
            git commit -m '[CircleCI] updated corporate logo'
            $SHELL -l -c "git push https://${GITHUB_TOKEN}@github.com/InnovAnon-Inc/InnovAnon-Inc.github.io.git"

workflows:
  version: 2.1
  commit:
    jobs:
      - build
  #approval:
  #  jobs:
  #    - hold:
  #        type: approval
      #- deploy:
      #    requires:
      #      - hold

