version: 2.1
jobs:
  build:
    docker: 
      #- image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      #- image: innovanon/poobuntu-ci:latest
      - image: innovanon/builder
    #parallelism: 4
    steps:
      - run:
          name: Import GPG Key
          command: |
            set -exu
            echo -e "$GPG_KEY" | gpg --import
      - run:
          name: Install Build Deps
          command: |
            set -exu
            #apt-fast install bc imagemagick caca-utils stegosuite zpaq lrzip makeself tor torsocks shellcheck makeself
            $SHELL -l apt update
            $SHELL -l apt install bc imagemagick caca-utils zpaq lrzip makeself shellcheck makeself
            # steghide stegosuite outguess
      - run:
          name: Increase Resource Limits
          command: |
            set -exu
            sed -i 's#^\( *<policy domain="resource" name="disk" value="\).*\("/>\)$#\110GiB\1#'  /etc/ImageMagick-6/policy.xml
            sed -i 's#^\( *<policy domain="resource" name="memory" value="\).*\("/>\)$#\11GiB\1#' /etc/ImageMagick-6/policy.xml
      - run:
          name: Checkout Project
          command: |
            $SHELL -l git clone --recursive https://github.com/InnovAnon-Inc/${CIRCLE_PROJECT_REPONAME}.git
#      - run:
#          name: Test Project
#          command: |
#            cd ${CIRCLE_PROJECT_REPONAME}
#            #PACKAGE=${CIRCLE_PROJECT_REPONAME,,}
#            #
#            #[ ! -z "`git tag`" ] || git tag v1.0
#            #git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' || git tag v1.0
#            ##revisioncount=$(expr `git log --oneline | wc -l` + 1)
#            #revisioncount=`git log --oneline | wc -l`
#            #cleanversion="`git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//`"
#            #VERSION="$cleanversion.$revisioncount"
#            
#            rm -v LICENSE README.md
#            #tar cf archive.tar --exclude archive.tar .
#            #tar cf -                  \
#            #  --exclude archive.tar   \
#            #  --exclude .circleci     \
#            #  --exclude-vcs           \
#            #  --exclude-vcs-ignores   \
#            #  --absolute-names        \
#            #  --group=nogroup         \
#            #  --mtime=0               \
#            #  --no-acls               \
#            #  --numeric-owner         \
#            #  --owner=nobody          \
#            #  --sort=name             \
#            #  --sparse              . |
#            #( mkdir -v /tmp/archive &&
#            #  cd       /tmp/archive &&
#            #  tar xf   - )
#            #makeself --nocomp /tmp/archive archive.tar quine \
#            #make -j$(nproc)
#            ##env RECP=InnovAnon-Inc@protonmail.com make -j$(nproc)
#            make release # test
      - run:
          name: Build Project (Shiva)
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}
            #RECP=InnovAnon-Inc@protonmail.com make -j$(nproc)
            #./dist.sh
            #$SHELL -l
            make -j$(nproc)
            #make -j$(nproc)
            #make -j$(nproc) clean
            #mkdir -v   /tmp/shiva
            #mv    -v * /tmp/shiva/
      - run:
          name: Release Project
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}
            #make -j$(nproc) clean
            #rm -v Makefile *.url LICENSE README.md
            #rm -rf *
            #mv -v /tmp/shiva/*  .
            #rm -v Makefile .Makefile make support* nohup.out *.url *.jpg *.mk archive.* .gitignore
            #tar xvf /tmp/logo.txz
            #rm -v   /tmp/logo.txz
            #rm -rf .git .circleci
            
            mkdir -v    /tmp/logo
            cp -v out/* /tmp/logo/
            cd          /tmp/logo

            for k in * ; do
              gpg --local-user 53F31F9711F06089\! --sign $k
            done

            cd ${CIRCLE_PROJECT_REPONAME}
            #rm -rf *
            #mv -v /tmp/logo/* .


            PACKAGE=${CIRCLE_PROJECT_REPONAME,,}

            [ ! -z "`git tag`" ] || git tag v1.0
            git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' || git tag v1.0
            #revisioncount=$(expr `git log --oneline | wc -l` + 1)
            revisioncount=`git log --oneline | wc -l`
            cleanversion="`git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//`"
            VERSION="$cleanversion.$revisioncount"

            #mkdir -v   ../tmp
            #mv    -v * ../tmp
            #ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} ../tmp
            $SHELL -l ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} /tmp/logo

            #git remote set-url origin https://github.com:${GITHUB_TOKEN}@github.com/InnovAnon-Inc/${CIRCLE_PROJECT_REPONAME}.git
            #git tag v$VERSION
            #git push
            #git push --tags
            #
            #github-release release --security-token $GITHUB_TOKEN --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME \
            #  --tag v$VERSION
            #
            #for k in * ; do
            #github-release upload  --security-token $GITHUB_TOKEN --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME \
            #  --tag v$VERSION --name $k --file $k
            #done
      - run:
          name: Update Home Page
          command: |
            # push to upstream
            $SHELL -l git clone --depth=1 --recursive https://github.com/InnovAnon-Inc/InnovAnon-Inc.github.io.git
            cd                                                               InnovAnon-Inc.github.io
            cp -v ../tmp/favicon.ico             assets/images/favicon.ico
            cp -v ../tmp/logo-visible.png        assets/images/logo.png
            cp -v ../tmp/logo-visible.png               images/3600x3600.png
            # manually managed image: math on black
            #cp -v ../tmp/logo-midvisible.png    assets/images/3600x3600.png
            cp -v ../tmp/logo-stego-animated.gif assets/images/logo.gif
            git config --global user.email "InnovAnon-Inc@gmail.com"
            git config --global user.name  "Innovations Anonymous"
            git add .
            git commit -m '[CircleCI] updated corporate logo'
            $SHELL -l git push "https://${GITHUB_TOKEN}@github.com/InnovAnon-Inc/InnovAnon-Inc.github.io.git"

workflows:
  version: 2.1
  commit:
    jobs:
      - build
  #approval:
  #  jobs:
  #    - hold:
  #        type: approval
      #- deploy:
      #    requires:
      #      - hold

