version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name:    Installing Binary Calculator and Parallel Gzip
          command: sudo apt install -qy bc pigz
      - run:
          name:    Increasing Resource Limits for ImageMagick
          command: sudo sed -i 's#^\( *<policy domain="resource" name="\(disk\|memory\)" value="\).*\("/>\)$#\110GiB\3#' /etc/ImageMagick-6/policy.xml
      - run:
          name:    Making the Project
          command: make -j`nproc`
      - run:
          name:    Cleanup
          command: make -j`nproc` clean
      - store_artifacts:
          path: logo.png
      - store_artifacts:
          path: logo-visible.png
      - store_artifacts:
          path: logo-animated.gif
      - store_artifacts:
          path: apple-touch-icon-120x120.png
      - store_artifacts:
          path: apple-touch-icon-152x152.png
      - store_artifacts:
          path: apple-touch-icon-60x60.png
      - store_artifacts:
          path: apple-touch-icon-76x76.png
      - store_artifacts:
          path: syslinux-splash.bmp
      - store_artifacts:
          path: grub-splash.xpm.gz
      - store_artifacts:
          path: favicon.ico

