version: 2.1
jobs:
  build:
    docker: 
      #- image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      #- image: innovanon/poobuntu-ci:latest
      - image: innovanon/logo-builder-ci
    #parallelism: 4
    steps:
      - run:
          name: Import GPG Key
          command: |
            set -u
            echo -e "$GPG_KEY" | \
            gpg --import
#      - run:
#          name: Install Build Deps
#          command: |
#            set -u
#            . /etc/profile
#            command -v support
#            apt update
#            echo success
#            exit 2
#            #apt-fast install bc imagemagick caca-utils stegosuite zpaq lrzip makeself tor torsocks shellcheck makeself
#            $SHELL -l -c 'apt update'
#            $SHELL -l -c 'apt full-upgrade'
#            $SHELL -l -c 'apt install bc imagemagick caca-utils zpaq lrzip makeself shellcheck makeself git ca-certificates golang'
#            $SHELL -l -c "env GOPATH=${HOME}/go PATH=${PATH}:${HOME}/go/bin go get -u github.com/tcnksm/ghr"
#            # steghide stegosuite outguess
#      - run:
#          name: Increase Resource Limits
#          command: |
#            set -exu
#            sed -i 's#^\( *<policy domain="resource" name="disk" value="\).*\("/>\)$#\110GiB\1#'  /etc/ImageMagick-6/policy.xml
#            sed -i 's#^\( *<policy domain="resource" name="memory" value="\).*\("/>\)$#\11GiB\1#' /etc/ImageMagick-6/policy.xml
      - run:
          name: Checkout Project
          command: |
            $SHELL -l -c "git clone --recursive https://github.com/InnovAnon-Inc/${CIRCLE_PROJECT_REPONAME}.git"
#      - run:
#          name: Test Project
#          command: |
#            cd ${CIRCLE_PROJECT_REPONAME}
#            #PACKAGE=${CIRCLE_PROJECT_REPONAME,,}
#            #
#            #[ ! -z "`git tag`" ] || git tag v1.0
#            #git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' || git tag v1.0
#            ##revisioncount=$(expr `git log --oneline | wc -l` + 1)
#            #revisioncount=`git log --oneline | wc -l`
#            #cleanversion="`git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//`"
#            #VERSION="$cleanversion.$revisioncount"
#            
#            rm -v LICENSE README.md
#            #tar cf archive.tar --exclude archive.tar .
#            #tar cf -                  \
#            #  --exclude archive.tar   \
#            #  --exclude .circleci     \
#            #  --exclude-vcs           \
#            #  --exclude-vcs-ignores   \
#            #  --absolute-names        \
#            #  --group=nogroup         \
#            #  --mtime=0               \
#            #  --no-acls               \
#            #  --numeric-owner         \
#            #  --owner=nobody          \
#            #  --sort=name             \
#            #  --sparse              . |
#            #( mkdir -v /tmp/archive &&
#            #  cd       /tmp/archive &&
#            #  tar xf   - )
#            #makeself --nocomp /tmp/archive archive.tar quine \
#            #make -j$(nproc)
#            ##env RECP=InnovAnon-Inc@protonmail.com make -j$(nproc)
#            make release # test
      - run:
          name: Build Project
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}
            #RECP=InnovAnon-Inc@protonmail.com make -j$(nproc)
            #./dist.sh
            #$SHELL -l -c "make -j$(nproc)"
            # TODO
            $SHELL -l -c "make -j1"
            #make -j$(nproc)
            #make -j$(nproc) clean
            #mkdir -v   /tmp/shiva
            #mv    -v * /tmp/shiva/
      - run:
          name: Sign Project
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}
            #make -j$(nproc) clean
            #rm -v Makefile *.url LICENSE README.md
            #rm -rf *
            #mv -v /tmp/shiva/*  .
            #rm -v Makefile .Makefile make support* nohup.out *.url *.jpg *.mk archive.* .gitignore
            #tar xvf /tmp/logo.txz
            #rm -v   /tmp/logo.txz
            #rm -rf .git .circleci
           
            cp sign.sh /usr/local/bin
            
            mkdir -v    /tmp/logo
            mv -v out/* /tmp/logo/
            cd          /tmp/logo

            sign.sh
            #find . \! -type d | xargs -P$(nproc) -n1 gpg --local-user 53F31F9711F06089\! --sign $k
            #for k in * ; do
            #  gpg --local-user 53F31F9711F06089\! --sign $k
            #done
      - run:
          name: Release Project
          command: |
            cd ${CIRCLE_PROJECT_REPONAME}
            #rm -rf *
            #mv -v /tmp/logo/* .


            PACKAGE=${CIRCLE_PROJECT_REPONAME,,}

            [ ! -z "`git tag`" ] || git tag v1.0
            git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' || git tag v1.0
            #revisioncount=$(expr `git log --oneline | wc -l` + 1)
            revisioncount=`git log --oneline | wc -l`
            cleanversion="`git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//`"
            VERSION="$cleanversion.$revisioncount"

            #mkdir -v   ../tmp
            #mv    -v * ../tmp
            #ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} ../tmp
            $SHELL -l -c "env GOPATH=${HOME}/go PATH=${PATH}:${HOME}/go/bin ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v${VERSION} /tmp/logo"

            #git remote set-url origin https://github.com:${GITHUB_TOKEN}@github.com/InnovAnon-Inc/${CIRCLE_PROJECT_REPONAME}.git
            #git tag v$VERSION
            #git push
            #git push --tags
            #
            #github-release release --security-token $GITHUB_TOKEN --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME \
            #  --tag v$VERSION
            #
            #for k in * ; do
            #github-release upload  --security-token $GITHUB_TOKEN --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME \
            #  --tag v$VERSION --name $k --file $k
            #done
      - run:
          name: Update Home Page
          command: |
            # push to upstream
            $SHELL -l -c 'git clone --depth=1 --recursive https://github.com/InnovAnon-Inc/InnovAnon-Inc.github.io.git'
            cd                                                                             InnovAnon-Inc.github.io
            #cp -v ../tmp/logo/favicon.ico             assets/images/favicon.ico
            #cp -v ../tmp/logo/logo-visible.png        assets/images/logo.png
            #cp -v ../tmp/logo/logo-visible.png               images/3600x3600.png

            cd assets/images
            ln -sv logo-visible.png 3600x3600.png
            ln -sv logo-visible.png logo.png
            cd ../..

#                  apple-touch-icon-114x114-precomposed.png \
#                  apple-touch-icon-120x120-precomposed.png \
#                  apple-touch-icon-144x144-precomposed.png \
#                  apple-touch-icon-152x152-precomposed.png \
#                  apple-touch-icon-180x180-precomposed.png \
#                  apple-touch-icon-57x57-precomposed.png   \
#                  apple-touch-icon-60x60-precomposed.png   \
#                  apple-touch-icon-72x72-precomposed.png   \
#                  apple-touch-icon-76x76-precomposed.png   \
#                  apple-touch-icon-precomposed.png         \
#                  bio-photo.jpg                            \
#                  apple-touch-icon.png                     \
            cp -v android-chrome-144x144.png               \
                  android-chrome-192x192.png               \
                  android-chrome-256x256.png               \
                  android-chrome-36x36.png                 \
                  android-chrome-384x384.png               \
                  android-chrome-48x48.png                 \
                  android-chrome-72x72.png                 \
                  android-chrome-96x96.png                 \
                  apple-touch-icon-114x114.png             \
                  apple-touch-icon-120x120.png             \
                  apple-touch-icon-144x144.png             \
                  apple-touch-icon-152x152.png             \
                  apple-touch-icon-180x180.png             \
                  apple-touch-icon-57x57.png               \
                  apple-touch-icon-60x60.png               \
                  apple-touch-icon-72x72.png               \
                  apple-touch-icon-76x76.png               \
                  favicon-16x16.png                        \
                  favicon-194x194.png                      \
                  favicon-32x32.png                        \
                  favicon.ico                              \
                  mstile-144x144.png                       \
                  mstile-150x150.png                       \
                  mstile-310x150.png                       \
                  mstile-310x310.png                       \
                  mstile-70x70.png                         \
                  safari-pinned-tab.svg                    \
                  assets/images/










            # manually managed image: math on black
            #cp -v ../tmp/logo-midvisible.png    assets/images/3600x3600.png
            #cp -v ../tmp/logo/logo-stego-animated.gif assets/images/logo.gif
            cp -v ../tmp/logo/logo-small-animated.gif assets/images/logo.gif
            git config --global user.email "InnovAnon-Inc@gmail.com"
            git config --global user.name  "Innovations Anonymous"
            git add .
            git commit -m '[CircleCI] updated corporate logo'
            $SHELL -l -c "git push https://${GITHUB_TOKEN}@github.com/InnovAnon-Inc/InnovAnon-Inc.github.io.git"

workflows:
  version: 2.1
  commit:
    jobs:
      - build
  #approval:
  #  jobs:
  #    - hold:
  #        type: approval
      #- deploy:
      #    requires:
      #      - hold

