version: 2.1
jobs:
  build:
    docker: 
      #- image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      - image: innovanon/poobuntu-ci:latest
    parallelism: 4
    steps:
      - run:
          command: |
            set -exu
            apt-fast install bc imagemagick
            sed -i 's#^\( *<policy domain="resource" name="disk" value="\).*\("/>\)$#\110GiB\1#' /etc/ImageMagick-6/policy.xml
            sed -i 's#^\( *<policy domain="resource" name="memory" value="\).*\("/>\)$#\11GiB\1#' /etc/ImageMagick-6/policy.xml

            git clone --recursive https://github.com/InnovAnon-Inc/${CIRCLE_PROJECT_REPONAME}.git
            cd ${CIRCLE_PROJECT_REPONAME}
            PACKAGE=${CIRCLE_PROJECT_REPONAME,,}

            [ ! -z "`git tag`" ] || git tag v1.0
            git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' || git tag v1.0
            revisioncount=`git log --oneline | wc -l`
            cleanversion="`git describe --tags --long | grep -o '^v[^.]*\.[^.-]*' | sed s/^v//`"
            VERSION="$cleanversion.$revisioncount"

            make -j2

            make -j2 clean
            rm -v Makefile *.url LICENSE README.md .gitignore
            rm -rf .git .circleci

            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} v${VERSION} .

